import { getUser, readRecords } from "@/lib/supabase/supabaseActions";
import React from "react";
import SignoutButton from "@/app/auth/_components/signout-button";
import DisplayPathname from "@/app/auth/_components/display-pathname";

const Page = async () => {
  const { user } = await getUser();
  const { data, error } = await readRecords("tasks");

  console.log(data, error);
  return (
    <div className="py-10 px-5 min-h-dvh w-full bg-neutral-50 flex flex-col items-center justify-center">
      <div className="max-w-2xl w-full bg-white rounded-lg shadow-lg p-5 border-2 border-neutral-50">
        <h1 className="font-bold">
          This page is protected with Supabase authentication.
        </h1>
        <code className="mt-1 text-sm">
          You can edit this page at <DisplayPathname />
          /page.tsx
        </code>
        <div className="mt-5 flex gap-2 items-center text-sm bg-gray-800 w-fit pl-3 pr-5 pt-4 rounded-t-lg text-white pb-2">
          {/* Make this an Image component for better performance */}
          <img
            alt="user image"
            src={
              user?.user_metadata?.avatar_url || user?.user_metadata?.picture
            }
            height={512}
            width={512}
            className="w-8 h-8 rounded-full"
          />
          <div className="flex flex-col">
            <p>{user?.email}</p>
            <p className="font-bold">{user?.user_metadata?.full_name}</p>
          </div>
        </div>

        <pre className="overflow-x-auto p-4 bg-gray-800 text-white text-xs rounded-tr-lg rounded-b-lg">
          <code>{JSON.stringify(user, null, 2)}</code>
        </pre>

        <SignoutButton>
          <button className="px-3 mt-5 py-2 w-full bg-black rounded active:scale-[0.98] transition-all duration-150 shadow text-white">
            Sign out
          </button>
        </SignoutButton>
      </div>
      <p className="mt-4 text-sm text-neutral-700">
        Auto-generated by next-mods (
        <a
          className="hover:underline text-blue-800"
          href="https://next-mods.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          next-mods.com
        </a>
        )
      </p>
    </div>
  );
};

export default Page;
